[package]
name = "charts-rs-web"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.19"
axum-client-ip = "0.4.1"
charts-rs = { version = "0.1.14", features = ["image"] }
chrono = "0.4.26"
config = { version = "0.13.3", features = ["yaml"] }
glob = "0.3.1"
hex = "0.4.3"
hyper = "0.14.27"
image = "0.24.6"
imagequant = { version = "4.2.0", default-features = false }
lodepng = "3.7.2"
mime = "0.3.17"
once_cell = "1.18.0"
rgb = "0.8.36"
rust-embed = { version = "6.8.1", features = ["mime-guess", "compression"] }
serde = "1.0.174"
serde_json = "1.0.103"
snafu = "0.7.5"
time = "0.3.23"
tokio = { version = "1.29.1", features = ["macros", "rt", "rt-multi-thread", "net", "signal"] }
tower = { version = "0.4.13", features = ["timeout"]}
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["local-time"] }
urlencoding = "2.1.2"
validator = { version = "0.16.1", features = ["derive"] }

[profile.release]
codegen-units = 1
lto = true
